import type { IEmployee } from "./employee";

export const initialData: IEmployee[] = [
  {
    id: "1",
    name: "Nguyen Van A",
    dateOfBirth: "1995-01-01",
    gender: "Male",
    email: "a@example.com",
    address: "Hanoi",
  },
  {
    id: "2",
    name: "Tran Thi B",
    dateOfBirth: "1998-05-12",
    gender: "Female",
    email: "b@example.com",
    address: "HCM",
  },
  {
    id: "3",
    name: "Le Van C",
    dateOfBirth: "1992-03-15",
    gender: "Male",
    email: "c@example.com",
    address: "Danang",
  },
  {
    id: "4",
    name: "Pham Thi D",
    dateOfBirth: "2000-07-20",
    gender: "Female",
    email: "d@example.com",
    address: "Hue",
  },
  {
    id: "5",
    name: "Hoang Van E",
    dateOfBirth: "1997-11-30",
    gender: "Male",
    email: "e@example.com",
    address: "Can Tho",
  },
  {
    id: "6",
    name: "Nguyen Thi F",
    dateOfBirth: "1996-09-05",
    gender: "Female",
    email: "f@example.com",
    address: "Hai Phong",
  },
  {
    id: "7",
    name: "Le Van G",
    dateOfBirth: "1993-02-18",
    gender: "Male",
    email: "g@example.com",
    address: "Nha Trang",
  },
  {
    id: "8",
    name: "Tran Thi H",
    dateOfBirth: "1999-12-25",
    gender: "Female",
    email: "h@example.com",
    address: "Vung Tau",
  },
  {
    id: "9",
    name: "Pham Van I",
    dateOfBirth: "1994-06-10",
    gender: "Male",
    email: "i@example.com",
    address: "Da Lat",
  },
  {
    id: "10",
    name: "Hoang Thi J",
    dateOfBirth: "2001-08-08",
    gender: "Female",
    email: "j@example.com",
    address: "Quang Ninh",
  },
];
